### ISSUE TITLE
vertical line in the startup page

### ISSUE THREAD

**Issue by osbm** [khaneliman/khanelivim#7]
![image](https://github.com/user-attachments/assets/bec25093-0a82-4d1f-910f-84e1d93dccd0)
Is this intentional? Is it to help indicate the line has been too long?

**Comment by khaneliman** [comment]
That would be coming from smartcolumn. Fixed in https://github.com/khaneliman/khanelivim/commit/dcc5d254abd9201eea723189d33b5239aa846a0c
